CREATE DATABASE CONCUNG
GO

USE CONCUNG
GO

CREATE TABLE SANPHAM
(
	MASP CHAR(10),
	LOAISP NVARCHAR(100),
	TENSP NVARCHAR(100),
	TENTHUONGHIEU NVARCHAR(100),
	XUATXUTHUONGHIEU NVARCHAR(100),
	XUATXUSP NVARCHAR(100),
	SOLUONGTRONGKHO INT
	CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP)
)
GO

CREATE TABLE DONHANG
(
	MADH CHAR(10),
	MAKH CHAR(10),
	TIENHANG MONEY,
	PHIVANCHUYEN MONEY,
	TONGTIEN MONEY,
	PHUONGTHUCTHANHTOAN NVARCHAR(20),
	MANV CHAR(10)
	CONSTRAINT PK_DONGHANG PRIMARY KEY(MADH)
)
GO

CREATE TABLE KHACHHANG
(
	MAKH CHAR(10),
	HOTEN NVARCHAR(40),
	SODT CHAR(10),
	DIACHI NVARCHAR(200)
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
)
GO

CREATE TABLE CT_DONHANG
(
	MASP CHAR(10),
	MADH CHAR(10),
	SOLUONG INT,
	THANHTIEN MONEY
	CONSTRAINT PK_CTDONHANG PRIMARY KEY(MASP, MADH)
)
GO

CREATE TABLE NHAPKHO
(
	MANHAPKHO CHAR(10),
	NGAYNHAP DATETIME,
	TONGSOLUONGNHAP INT,
	CONSTRAINT PL_NHAPKHO PRIMARY KEY(MANHAPKHO)
)
GO

CREATE TABLE CT_NHAPKHO
(
	MASP CHAR(10),
	MANHAPKHO CHAR(10),
	SOLUONGNHAP INT,
	CONSTRAINT PK_CTNHAPKHO PRIMARY KEY(MASP, MANHAPKHO)
)
GO

CREATE TABLE GIAOHANG
(
	MAGH CHAR(10),
	DONVIGIAOHANG NVARCHAR(100),
	NGAYGIAO DATETIME,
	NGAYKHACHNHANHANG DATETIME
	CONSTRAINT PK_GIAOHANG PRIMARY KEY(MAGH)
)
GO

CREATE TABLE CT_GIAOHANG
(
	MADH CHAR(10),
	MAGH CHAR(10)
	CONSTRAINT PK_CTGIAOHANG PRIMARY KEY(MADH, MAGH)
)
GO

CREATE TABLE NHANVIEN
(
	MANV CHAR(10),
	HOTEN NVARCHAR(30),
	LUONG MONEY,
	DOANHSO MONEY,
	CHITIEU MONEY,
	MACUAHANG CHAR(10)
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
)
GO

CREATE TABLE CUAHANG
(
	MACUAHANG CHAR(10),
	DOANHSO MONEY,
	CHITIEU MONEY
	CONSTRAINT PK_CUAHANG PRIMARY KEY(MACUAHANG)
)
GO

CREATE TABLE DIEMDANH
(
	MANV CHAR(10),
	NGAYDIEMDANH BIT
	CONSTRAINT PK_DIEMDANH PRIMARY KEY(MANV, NGAYDIEMDANH)
)
GO

CREATE TABLE LICHSULUONG
(
	MANV CHAR(10),
	NGAYTHAYDOILUONG DATETIME,
	LUONGCU MONEY
	CONSTRAINT PK_LICHSULUONG PRIMARY KEY(MANV, NGAYTHAYDOILUONG)
)
GO

ALTER TABLE CT_NHAPKHO
ADD CONSTRAINT FK_CT_NHAPKHO_SANPHAM
FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)

ALTER TABLE CT_NHAPKHO
ADD CONSTRAINT FK_CT_NHAPKHO_NHAPKHO
FOREIGN KEY(MANHAPKHO) REFERENCES NHAPKHO(MANHAPKHO)

ALTER TABLE CT_DONHANG
ADD CONSTRAINT FK_CT_DONHANG_SANPHAM
FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)

ALTER TABLE CT_DONHANG
ADD CONSTRAINT FK_CT_DONHANG_DONHANG
FOREIGN KEY(MADH) REFERENCES DONHANG(MADH)

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_KHACHHANG
FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_NHANVIEN
FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CT_GIAOHANG
ADD CONSTRAINT FK_CT_GIAOHANG_DONHANG
FOREIGN KEY(MADH) REFERENCES DONHANG(MADH)

ALTER TABLE CT_GIAOHANG
ADD CONSTRAINT FK_CT_GIAOHANG_GIAOHANG
FOREIGN KEY(MAGH) REFERENCES GIAOHANG(MAGH)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN0_CUAHANG
FOREIGN KEY(MACUAHANG) REFERENCES CUAHANG(MACUAHANG)

ALTER TABLE DIEMDANH
ADD CONSTRAINT FK_DIEMDANH_NHANVIEN
FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE LICHSULUONG
ADD CONSTRAINT FK_LICHSULUONG_NHANVIEN
FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)