USE master
GO

DROP DATABASE CONCUNG
GO

CREATE DATABASE CONCUNG
GO

USE CONCUNG
GO

CREATE TABLE SANPHAM
(
	MASP CHAR(10),
	TENSP NVARCHAR(100),
	GIABAN MONEY,
	TENTHUONGHIEU NVARCHAR(100),
	XUATXUTHUONGHIEU NVARCHAR(100),
	XUATXUSP NVARCHAR(100),
	IMAGEURL CHAR(256), -- URL CUA ANH
	MOTASP VARCHAR(max),  --VARCHAR ĐỂ DỄ GENERATE DỮ LIỆU LỚN( STRING 8000 KÍ TỰ )
	MALOAI CHAR(10),
	CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP)
)
GO

CREATE TABLE LOAISP
(
	MALOAI CHAR(10),
	TENLOAI NVARCHAR(64),
	IMAGEURL CHAR(256)
	CONSTRAINT PK_LOAISP PRIMARY KEY(MALOAI)
)

GO
CREATE TABLE DONHANG
(
	MADH CHAR(10),
	MAKH CHAR(10),
	TIENHANG MONEY,
	PHIVANCHUYEN MONEY,
	TONGTIEN MONEY,
	NVLAPDH CHAR(10),
	NGAYLAP DATE,
	TRANGTHAI BIT, -- TINH TRANG CUA DON HANG
	CONSTRAINT PK_DONGHANG PRIMARY KEY(MADH)
)
GO

CREATE TABLE KHACHHANG
(
	MAKH CHAR(10),
	HOTEN NVARCHAR(100),
	SDT CHAR(10),
	DIACHI NVARCHAR(300),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
)
GO

CREATE TABLE CT_DONHANG
(
	MADH CHAR(10),
	MASP CHAR(10),
	SOLUONG INT,
	THANHTIEN MONEY
	CONSTRAINT PK_CTDONHANG PRIMARY KEY(MADH, MASP)
)
GO

CREATE TABLE NHAPKHO
(
	MACUAHANG CHAR(10),
	MANHAPKHO CHAR(10),
	MAKHO CHAR(10),
	MASP CHAR(10),
	NGAYNHAP DATE,
	SOLUONGNHAP INT,
	CONSTRAINT PK_NHAPKHO PRIMARY KEY(MANHAPKHO, MACUAHANG, MAKHO, MASP)
)
GO

CREATE TABLE NHANVIEN
(
	MANV CHAR(10),
	HOTEN NVARCHAR(100),
	LUONG MONEY,
	DOANHSO MONEY,
	CHITIEU MONEY,
	MACUAHANG CHAR(10)
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
)
GO


CREATE TABLE CUAHANG
(
	MACUAHANG CHAR(10),
	DOANHSO MONEY,
	CHITIEU MONEY, 
	DIACHI NVARCHAR(300)
	CONSTRAINT PK_CUAHANG PRIMARY KEY(MACUAHANG)
)
GO

CREATE TABLE DIEMDANH
(
	MANV CHAR(10),
	NGAYDIEMDANH DATE
	CONSTRAINT PK_DIEMDANH PRIMARY KEY(MANV, NGAYDIEMDANH)
)
GO

CREATE TABLE LICHSULUONG
(
	MANV CHAR(10),
	NGAYTHAYDOILUONG DATE,
	LUONGCU MONEY
	CONSTRAINT PK_LICHSULUONG PRIMARY KEY(MANV, NGAYTHAYDOILUONG)
)
GO

CREATE TABLE KHO
(
	MACUAHANG CHAR(10),
	MAKHO CHAR(10),
	MASP CHAR(10),
	SOLUONGTON INT
	CONSTRAINT PK_KHO PRIMARY KEY (MACUAHANG, MAKHO, MASP)
)

GO


ALTER TABLE CT_DONHANG
ADD CONSTRAINT FK_CT_DONHANG_SANPHAM
FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
GO

ALTER TABLE CT_DONHANG
ADD CONSTRAINT FK_CT_DONHANG_DONHANG
FOREIGN KEY(MADH) REFERENCES DONHANG(MADH)
GO

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_KHACHHANG
FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
GO

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_NHANVIEN
FOREIGN KEY(NVLAPDH) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_CUAHANG
FOREIGN KEY(MACUAHANG) REFERENCES CUAHANG(MACUAHANG)
GO

ALTER TABLE DIEMDANH
ADD CONSTRAINT FK_DIEMDANH_NHANVIEN
FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE LICHSULUONG
ADD CONSTRAINT FK_LICHSULUONG_NHANVIEN
FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE KHO
ADD CONSTRAINT FK_KHO_CUAHANG
FOREIGN KEY(MACUAHANG) REFERENCES CUAHANG(MACUAHANG)
GO

ALTER TABLE KHO
ADD CONSTRAINT FK_KHO_SANPHAM
FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
GO

ALTER TABLE NHAPKHO
ADD CONSTRAINT FK_NHAPKHO_KHO
FOREIGN KEY(MACUAHANG, MAKHO, MASP) REFERENCES KHO(MACUAHANG, MAKHO, MASP)
GO

ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SANPHAM_LOAI
FOREIGN KEY(MALOAI) REFERENCES LOAISP(MALOAI)
GO


