use CONCUNG
GO

CREATE TABLE HOTEN
(
    ID INT,
    HO NVARCHAR(100),
    TENDEM NVARCHAR(100),
    TEN NVARCHAR(100),
)

CREATE TABLE DIACHI(
    ID INT,
    DUONG NVARCHAR(200),
    PHUONG NVARCHAR(200),
    QUAN NVARCHAR(200),
    TP NVARCHAR(200),
)

GO

BULK INSERT HOTEN
FROM '~\hovaten.txt'
WITH(
    CODEPAGE = '65001', 
    DATAFILETYPE = 'Char',
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n'
)
GO

BULK INSERT DIACHI
FROM 'diachi.txt'
WITH(
    CODEPAGE = '65001', 
    DATAFILETYPE = 'Char',
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n'
)
GO



-- https://stackoverflow.com/questions/1324063/generating-random-strings-with-t-sql


GO
CREATE PROC MAKE_STRING @LENGTH INT, @out Nvarchar(max) OUTPUT
AS 
BEGIN

    declare @BinaryData varbinary(max)

    set @BinaryData=crypt_gen_random(@Length) 

    set @out=cast('' as xml).value('xs:base64Binary(sql:variable("@BinaryData"))', 'varchar(max)')
END
GO

CREATE PROC INSERTKH @NUM INT
AS 
BEGIN
    DECLARE @MAKH CHAR(10), @HOTEN NVARCHAR(100), @SDT VARCHAR(10)
    DECLARE @DIACHI NVARCHAR(300), @COUNT INT = 0
    
    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT = @COUNT + 1

        SET @MAKH = 'KH' + CAST(@COUNT AS CHAR(8))

        SET @HOTEN = (SELECT HO FROM HOTEN 
            WHERE CAST(RAND()*100 AS INT) = ID) +' '+ (
            SELECT TENDEM FROM HOTEN 
            WHERE CAST(RAND()*100 AS int) = ID) +' '+ (
            SELECT TEN FROM HOTEN WHERE CAST(RAND()*100 AS INT) =ID)
        
        SET @SDT = '0' + CAST(CAST(RAND()*900000000+100000000 AS INT) AS CHAR(9))


        DECLARE @RAND INT, @TP NVARCHAR(100) = 'TP HỒ CHÍ MINH'
        SET @RAND = CAST(RAND()*3 AS INT)
        IF @RAND <= 2
        BEGIN
            SET @TP = (SELECT TP FROM DIACHI 
                WHERE ID = CAST(RAND()*61 AS INT))
        END

        SET @DIACHI = CAST(CAST(RAND()*100+1 AS INT) AS NVARCHAR(4)) +', '+ (
            SELECT DUONG FROM DIACHI 
            WHERE ID = CAST(RAND()*100 AS INT))+ ', ' + (
            SELECT PHUONG FROM DIACHI 
            WHERE ID = CAST(RAND()*100 AS INT)) +', '+ (
            SELECT QUAN FROM DIACHI 
            WHERE ID = CAST(RAND()*24 AS INT)) +', '+ @TP

        INSERT INTO KHACHHANG VALUES(@MAKH, @HOTEN, @SDT, @DIACHI)   
    END
END
GO

DELETE FROM KHACHHANG
EXEC INSERTKH 10


GO
DROP PROC INSERTSP
GO
CREATE PROCEDURE INSERTSP @NUM INT
AS BEGIN
    DECLARE @MASP CHAR(10), @LOAISP NVARCHAR(100)
    DECLARE @TENSP NVARCHAR(100), @GIA MONEY, @TENTH NVARCHAR(100)
    DECLARE @XUATXUTH NVARCHAR(100), @XUATXUSP NVARCHAR(100)
    DECLARE @MOTASP VARCHAR(MAX)
    DECLARE @COUNT INT = 0, @RANDLENGTH INT

    WHILE @COUNT < @NUM 
    BEGIN
        SET @COUNT += 1 
        
        SET @MASP = 'SP' + CAST(@COUNT AS CHAR(8))

        SET @RANDLENGTH = RAND()*80+20
        EXEC MAKE_STRING @RANDLENGTH, @LOAISP OUTPUT

        SET @RANDLENGTH = RAND()*80+20
        EXEC MAKE_STRING @RANDLENGTH, @TENSP OUTPUT

        SET @GIA = CAST(RAND()*1000+1 AS INT)

        SET @RANDLENGTH = RAND()*80+20
        EXEC MAKE_STRING @RANDLENGTH, @TENTH OUTPUT

        SET @RANDLENGTH = RAND()*80+20
        EXEC MAKE_STRING @RANDLENGTH, @XUATXUTH OUTPUT

        SET @RANDLENGTH = RAND()*80+20
        EXEC MAKE_STRING @RANDLENGTH, @XUATXUSP OUTPUT

        SET @RANDLENGTH = RAND()*6000+2000
        EXEC MAKE_STRING @RANDLENGTH, @MOTASP OUTPUT
        
        INSERT INTO SANPHAM VALUES(@MASP, @LOAISP, @TENSP, @GIA, @TENTH, @XUATXUTH, @XUATXUSP, @MOTASP)
    END
END
GO

DELETE FROM SANPHAM
GO

EXEC INSERTSP 10
GO

GO
CREATE PROC INSERTCH @NUM INT  
AS BEGIN
    DECLARE @MACH CHAR(10), @DOANHSO MONEY, @CHITIEU MONEY
    DECLARE @DIACHI  NVARCHAR(300), @COUNT INT = 0

    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT += 1 
        
        SET @MACH = 'CH' + CAST(@COUNT AS CHAR(8))

        SET @DOANHSO = CAST(CAST(RAND()*10000000+1000000 AS INT) AS MONEY)

        SET @CHITIEU = CAST(CAST(RAND()*15000000 + 1000000 AS INT) AS MONEY)

        DECLARE @RAND INT, @TP NVARCHAR(100) = 'TP HỒ CHÍ MINH'
        SET @RAND = CAST(RAND()*3 AS INT)
        IF @RAND <= 2
        BEGIN
            SET @TP = (SELECT TP FROM DIACHI 
                WHERE ID = CAST(RAND()*61 AS INT))
            
        END

        SET @DIACHI = CAST(CAST(RAND()*100+1 AS INT) AS NVARCHAR(4)) +', '+ (
            SELECT DUONG FROM DIACHI 
            WHERE ID = CAST(RAND()*100 AS INT))+ ', ' + (
            SELECT PHUONG FROM DIACHI 
            WHERE ID = CAST(RAND()*100 AS INT)) +', '+ (
            SELECT QUAN FROM DIACHI 
            WHERE ID = CAST(RAND()*24 AS INT)) +', '+ @TP

        INSERT INTO CUAHANG VALUES(@MACH, @DOANHSO, @CHITIEU, @DIACHI)
    END
END
GO

DELETE FROM CUAHANG
EXEC INSERTCH 10
GO

GO 
CREATE PROC INSERTNV @NUM INT
AS
BEGIN
    DECLARE @MANV CHAR(10), @HOTEN NVARCHAR(100), @LUONG MONEY, @MACH CHAR(10)
    DECLARE @DOANHSO MONEY, @CHITIEU MONEY, @COUNT INT = 0
    DECLARE @LENGTH INT = (SELECT COUNT(MACUAHANG) FROM CUAHANG)

    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT += 1 

        SET @MANV = 'NV' + CAST(@COUNT AS CHAR(8))
        
        SET @HOTEN = (SELECT HO FROM HOTEN 
            WHERE CAST(RAND()*100 AS INT) = ID) +' '+ (
            SELECT TENDEM FROM HOTEN 
            WHERE CAST(RAND()*100 AS int) = ID) +' '+ (
            SELECT TEN FROM HOTEN WHERE CAST(RAND()*100 AS INT) =ID)

        SET @LUONG = CAST(RAND()*50000+10000 AS INT)
        SET @DOANHSO = CAST(RAND()*100000+10000 AS INT)
        SET @CHITIEU = CAST(RAND()*120000 + 10000 AS INT)
        SET @MACH = 'CH' + CAST( CAST(RAND()*@LENGTH+1 AS INT) AS CHAR(8))
        
        INSERT INTO NHANVIEN VALUES(@MANV, @HOTEN, @LUONG, @DOANHSO, @CHITIEU, @MACH)
    END
END
GO

DELETE FROM NHANVIEN
EXEC INSERTNV 10

GO
CREATE PROC INSERTDIEMDANH @NUM INT
AS
BEGIN
    DECLARE @MANV CHAR(10), @NGAYDIEMDANH DATE
    DECLARE @COUNT INT = 0
    DECLARE @LENGTH INT = CAST((SELECT COUNT(MANV) FROM NHANVIEN)+1 AS INT)

    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT += 1
        SET @MANV = 'NV' + CAST( CAST(RAND()*@LENGTH+1 AS INT) AS CHAR(8))
        SET @NGAYDIEMDANH = DATEADD(DAY,ABS(CHECKSUM(NEWID())) % ( 1 + DATEDIFF(DAY,'2015-01-01','2021-12-31')),'2015-01-01')

        INSERT INTO DIEMDANH VALUES(@MANV, @NGAYDIEMDANH)
    END
END
GO


GO
CREATE PROC INSERTLSLUONG @NUM INT
AS BEGIN
    DECLARE @MANV CHAR(10), @NGAYDOILUONG DATE
    DECLARE @COUNT INT = 0, @LUONGCU MONEY
    DECLARE @LENGTH INT = CAST((SELECT COUNT(MANV) FROM NHANVIEN)+1 AS INT)

    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT += 1
        SET @MANV = 'NV' + CAST( CAST(RAND()*@LENGTH+1 AS INT) AS CHAR(8))
        SET @NGAYDOILUONG = DATEADD(DAY,ABS(CHECKSUM(NEWID())) % ( 1 + DATEDIFF(DAY,'2015-01-01','2021-12-31')),'2015-01-01')
        SET @LUONGCU = CAST(RAND()*40000+10000 AS INT)

        INSERT INTO LICHSULUONG VALUES(@MANV, @NGAYDOILUONG, @LUONGCU)
    END
END
GO




-- GO

-- ALTER PROC TEST @OUT CHAR(10) OUTPUT
-- AS BEGIN

--     DECLARE @TEMP CHAR(10) = '0'

--     DECLARE @COUNT1 INT = 1

--     WHILE @COUNT1 < 10
--     BEGIN
--         SET @COUNT1 +=1
--         SET @TEMP += CHAR(CAST (RAND() * (90-65) + 65 AS INT))
--     END

-- END 

-- GO

-- DECLARE @TEMP CHAR(10)
-- GO





-- DECLARE @TEMP CHAR(10) = '0'

-- DECLARE @COUNT1 INT = 1
-- DECLARE @TEMP1 VARCHAR(10) = '0'
-- WHILE @COUNT1 < 10
-- BEGIN
--     SET @COUNT1 +=1
--     SET @TEMP1 += CHAR(CAST (RAND() * 9 + 48 AS INT))
-- END
-- SET @TEMP = @TEMP1

-- PRINT @TEMP