use CONCUNG
GO

CREATE TABLE HOTEN
(
    ID INT,
    HO NVARCHAR(100),
    TENDEM NVARCHAR(100),
    TEN NVARCHAR(100),
)

CREATE TABLE DIACHI(
    ID INT,
    DUONG NVARCHAR(200),
    PHUONG NVARCHAR(200),
    QUAN NVARCHAR(200),
    TP NVARCHAR(200),
)

GO

BULK INSERT HOTEN
FROM '~\hovaten.txt'
WITH(
    CODEPAGE = '65001', 
    DATAFILETYPE = 'Char',
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n'
)
GO

BULK INSERT DIACHI
FROM 'diachi.txt'
WITH(
    CODEPAGE = '65001', 
    DATAFILETYPE = 'Char',
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n'
)
GO



-- https://stackoverflow.com/questions/1324063/generating-random-strings-with-t-sql


GO
CREATE PROC MAKE_STRING @LENGTH INT, @out Nvarchar(max) OUTPUT
AS 
BEGIN

    declare @BinaryData varbinary(max)

    set @BinaryData=crypt_gen_random(@Length) 

    set @out=cast('' as xml).value('xs:base64Binary(sql:variable("@BinaryData"))', 'varchar(max)')
END
GO

CREATE PROC INSERTKH @NUM INT
AS 
BEGIN
    DECLARE @MAKH CHAR(10), @HOTEN NVARCHAR(100), @SDT VARCHAR(10)
    DECLARE @DIACHI NVARCHAR(300), @COUNT INT = 0
    
    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT = @COUNT + 1

        SET @MAKH = 'KH' + CAST(@COUNT AS CHAR(8))

        SET @HOTEN = (SELECT HO FROM HOTEN 
            WHERE CAST(RAND()*100 AS INT) = ID) +' '+ (
            SELECT TENDEM FROM HOTEN 
            WHERE CAST(RAND()*100 AS int) = ID) +' '+ (
            SELECT TEN FROM HOTEN WHERE CAST(RAND()*100 AS INT) =ID)
        
        SET @SDT = '0' + CAST(CAST(RAND()*900000000+100000000 AS INT) AS CHAR(9))


        DECLARE @RAND INT, @TP NVARCHAR(100) = 'TP HỒ CHÍ MINH'
        SET @RAND = CAST(RAND()*3 AS INT)
        IF @RAND <= 2
        BEGIN
            SET @TP = (SELECT TP FROM DIACHI 
                WHERE ID = CAST(RAND()*61 AS INT))
        END

        SET @DIACHI = CAST(CAST(RAND()*100+1 AS INT) AS NVARCHAR(4)) +', '+ (
            SELECT DUONG FROM DIACHI 
            WHERE ID = CAST(RAND()*100 AS INT))+ ', ' + (
            SELECT PHUONG FROM DIACHI 
            WHERE ID = CAST(RAND()*100 AS INT)) +', '+ (
            SELECT QUAN FROM DIACHI 
            WHERE ID = CAST(RAND()*24 AS INT)) +', '+ @TP

        INSERT INTO KHACHHANG VALUES(@MAKH, @HOTEN, @SDT, @DIACHI)   
    END
END
GO

GO
CREATE PROCEDURE INSERTSP @NUM INT
AS BEGIN
    DECLARE @MASP CHAR(10), @LOAISP NVARCHAR(100)
    DECLARE @TENSP NVARCHAR(100), @GIA MONEY, @TENTH NVARCHAR(100)
    DECLARE @XUATXUTH NVARCHAR(100), @XUATXUSP NVARCHAR(100)
    DECLARE @MOTASP VARCHAR(MAX)
    DECLARE @COUNT INT = 0, @RANDLENGTH INT

    WHILE @COUNT < @NUM 
    BEGIN
        SET @COUNT += 1 
        
        SET @MASP = 'SP' + CAST(@COUNT AS CHAR(8))

        SET @RANDLENGTH = RAND()*80+20
        EXEC MAKE_STRING @RANDLENGTH, @LOAISP OUTPUT

        SET @RANDLENGTH = RAND()*80+20
        EXEC MAKE_STRING @RANDLENGTH, @TENSP OUTPUT

        SET @GIA = CAST(RAND()*1000+1 AS INT)

        SET @RANDLENGTH = RAND()*80+20
        EXEC MAKE_STRING @RANDLENGTH, @TENTH OUTPUT

        SET @RANDLENGTH = RAND()*80+20
        EXEC MAKE_STRING @RANDLENGTH, @XUATXUTH OUTPUT

        SET @RANDLENGTH = RAND()*80+20
        EXEC MAKE_STRING @RANDLENGTH, @XUATXUSP OUTPUT

        SET @RANDLENGTH = RAND()*6000+2000
        EXEC MAKE_STRING @RANDLENGTH, @MOTASP OUTPUT
        
        INSERT INTO SANPHAM VALUES(@MASP, @LOAISP, @TENSP, @GIA, @TENTH, @XUATXUTH, @XUATXUSP, @MOTASP)
    END
END
GO


GO
CREATE PROC INSERTCH @NUM INT  
AS BEGIN
    DECLARE @MACH CHAR(10), @DOANHSO MONEY, @CHITIEU MONEY
    DECLARE @DIACHI  NVARCHAR(300), @COUNT INT = 0

    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT += 1 
        
        SET @MACH = 'CH' + CAST(@COUNT AS CHAR(8))

        SET @DOANHSO = CAST(CAST(RAND()*10000000+1000000 AS INT) AS MONEY)

        SET @CHITIEU = CAST(CAST(RAND()*15000000 + 1000000 AS INT) AS MONEY)

        DECLARE @RAND INT, @TP NVARCHAR(100) = 'TP HỒ CHÍ MINH'
        SET @RAND = CAST(RAND()*3 AS INT)
        IF @RAND <= 2
        BEGIN
            SET @TP = (SELECT TP FROM DIACHI 
                WHERE ID = CAST(RAND()*61 AS INT))
            
        END

        SET @DIACHI = CAST(CAST(RAND()*100+1 AS INT) AS NVARCHAR(4)) +', '+ (
            SELECT DUONG FROM DIACHI 
            WHERE ID = CAST(RAND()*100 AS INT))+ ', ' + (
            SELECT PHUONG FROM DIACHI 
            WHERE ID = CAST(RAND()*100 AS INT)) +', '+ (
            SELECT QUAN FROM DIACHI 
            WHERE ID = CAST(RAND()*24 AS INT)) +', '+ @TP

        INSERT INTO CUAHANG VALUES(@MACH, @DOANHSO, @CHITIEU, @DIACHI)
    END
END
GO


GO 
CREATE PROC INSERTNV @NUM INT
AS
BEGIN
    DECLARE @MANV CHAR(10), @HOTEN NVARCHAR(100), @LUONG MONEY, @MACH CHAR(10)
    DECLARE @DOANHSO MONEY, @CHITIEU MONEY, @COUNT INT = 0
    DECLARE @LENGTH INT = (SELECT COUNT(MACUAHANG) FROM CUAHANG)

    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT += 1 

        SET @MANV = 'NV' + CAST(@COUNT AS CHAR(8))
        
        SET @HOTEN = (SELECT HO FROM HOTEN 
            WHERE CAST(RAND()*100 AS INT) = ID) +' '+ (
            SELECT TENDEM FROM HOTEN 
            WHERE CAST(RAND()*100 AS int) = ID) +' '+ (
            SELECT TEN FROM HOTEN WHERE CAST(RAND()*100 AS INT) =ID)

        SET @LUONG = CAST(RAND()*50000+10000 AS INT)
        SET @DOANHSO = CAST(RAND()*100000+10000 AS INT)
        SET @CHITIEU = CAST(RAND()*120000 + 10000 AS INT)
        SET @MACH = 'CH' + CAST( CAST(RAND()*@LENGTH+1 AS INT) AS CHAR(8))
        
        INSERT INTO NHANVIEN VALUES(@MANV, @HOTEN, @LUONG, @DOANHSO, @CHITIEU, @MACH)
    END
END
GO

GO
CREATE PROC INSERTDIEMDANH @NUM INT
AS
BEGIN
    DECLARE @MANV CHAR(10), @NGAYDIEMDANH DATE
    DECLARE @COUNT INT = 0
    DECLARE @LENGTH INT = (SELECT COUNT(MANV) FROM NHANVIEN)

    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT += 1
        SET @MANV = 'NV' + CAST( CAST(RAND()*@LENGTH+1 AS INT) AS CHAR(8))
        SET @NGAYDIEMDANH = DATEADD(DAY,ABS(CHECKSUM(NEWID())) % ( 1 + DATEDIFF(DAY,'2015-01-01','2021-12-31')),'2015-01-01')

        INSERT INTO DIEMDANH VALUES(@MANV, @NGAYDIEMDANH)
    END
END
GO


GO
CREATE PROC INSERTLSLUONG @NUM INT
AS BEGIN
    DECLARE @MANV CHAR(10), @NGAYDOILUONG DATE
    DECLARE @COUNT INT = 0, @LUONGCU MONEY
    DECLARE @LENGTH INT = CAST((SELECT COUNT(MANV) FROM NHANVIEN) AS INT)

    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT += 1
        SET @MANV = 'NV' + CAST( CAST(RAND()*@LENGTH+1 AS INT) AS CHAR(8))
        SET @NGAYDOILUONG = DATEADD(DAY,ABS(CHECKSUM(NEWID())) % ( 1 + DATEDIFF(DAY,'2015-01-01','2021-12-31')),'2015-01-01')
        SET @LUONGCU = CAST(RAND()*40000+10000 AS INT)

        INSERT INTO LICHSULUONG VALUES(@MANV, @NGAYDOILUONG, @LUONGCU)
    END
END
GO



GO 
CREATE PROC INSERTDH @NUM INT
AS BEGIN
    DECLARE @MADH CHAR(10), @MAKH CHAR(10)
    DECLARE @PHIVC MONEY, @PTTT NVARCHAR(100)
    DECLARE @MANV CHAR(10), @COUNT INT = 0
    DECLARE @LENGTHKH INT = (SELECT COUNT(MAKH) FROM KHACHHANG)
    DECLARE @LENGTHNV INT = (SELECT COUNT(MANV) FROM NHANVIEN)

    WHILE @COUNT < @NUM 
    BEGIN
        SET @COUNT += 1

        SET @MADH = 'DH' + CAST(@COUNT AS CHAR(8))
        SET @MAKH = 'KH' + CAST(CAST(RAND()*@LENGTHKH+1 AS INT) AS CHAR(8))
        SET @MANV = 'NV' + CAST(CAST(RAND()*@LENGTHNV+1 AS INT) AS CHAR(8))

        SET @PHIVC = CAST(RAND()*100 AS INT)
        SET @PTTT = N'Thanh toán khi nhận hàng'
        
        INSERT INTO DONHANG VALUES (@MADH, @MAKH, 0, @PHIVC,
            0, @PTTT, @MANV ,N'Đang lên đơn')
    END
END
GO



GO
CREATE PROC INSERTCT_DH
AS BEGIN
    DECLARE @MASP CHAR(10), @MADH CHAR(10), @SL INT
    DECLARE @COUNT INT = 0
    DECLARE @LENGTHSP INT = (SELECT COUNT(MASP) FROM SANPHAM)
    DECLARE @LENGTHDH INT = (SELECT COUNT(MADH) FROM DONHANG)
    DECLARE @NUM INT = @LENGTHDH
    DECLARE @COUNT1 INT, @NUM1 INT

    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT += 1
        SET @MADH = 'DH' + CAST(@COUNT AS CHAR(8))

        SET @COUNT1 = 0
        SET @NUM1 = CAST(RAND()*5+1 AS INT)

        WHILE @COUNT1 < @NUM1
        BEGIN
            SET @COUNT1 += 1

            SET @MASP = 'SP' + CAST(CAST(RAND()*@LENGTHSP +1 AS INT) AS CHAR(8))
            SET @SL = CAST(RAND()*100+1 AS INT)

            INSERT INTO CT_DONHANG VALUES(@MADH, @MASP, @SL, 0)
        END
    END
END
GO




GO
CREATE PROC INSERTGIAOHANG @NUM INT
AS BEGIN
    DECLARE @MADH CHAR(10), @MAGH CHAR(10)
    DECLARE @DONVIGH NVARCHAR(200), @COUNT INT = 0 
    DECLARE @LENGTHDH INT = (SELECT COUNT(MADH) FROM DONHANG)
    DECLARE @TRANGTHAI NVARCHAR(100) = N'Đang giao'
    DECLARE @LENGTH INT

    WHILE @COUNT < @NUM
    BEGIN
        SET @COUNT += 1

        SET @MAGH = 'GH' + CAST(@COUNT AS CHAR(8))
        SET @MADH = 'DH' + CAST(CAST(RAND()*@LENGTHDH + 1 AS INT) AS CHAR(8))

        SET @LENGTH = CAST(RAND()*200 AS INT)
        -- EXEC MAKE_STRING @LENGTH, @DONVIGH OUTPUT

        IF @COUNT > 90000 
        BEGIN
            SET @TRANGTHAI = N'Khách không nhận hàng' 
        END
        ELSE IF @COUNT > 50000
        BEGIN
            SET @TRANGTHAI = N'Đã giao'
        END

        INSERT INTO GIAOHANG VALUES (@MAGH, @MADH, @TRANGTHAI, 'Grab', NULL, NULL)
    END
END
GO


CREATE PROC INSERTKHO_NHAPKHO
AS BEGIN
    DECLARE @MACH CHAR(10), @MAKHO CHAR(10), @COUNT INT = 0
    DECLARE @MASP CHAR(10), @SL INT
    DECLARE @LENGTHCH INT = (SELECT COUNT(MACUAHANG) FROM CUAHANG)
    DECLARE @LENGTHSP INT = (SELECT COUNT(MASP) FROM SANPHAM)
    DECLARE @COUNT1 INT, @COUNT2 INT, @NUM1 INT, @NUM2 INT

    DECLARE @MANHAPKHO CHAR(10), @NGAYNHAP DATE, @SLNHAP INT

    DECLARE @STARTDATE DATE
    DECLARE @NK_DATE TABLE( MANK CHAR(10), NGAYNHAP DATE)

    WHILE @COUNT < @LENGTHCH
    BEGIN
        SET @COUNT +=1

        SET @MACH = 'CH' + CAST(@COUNT AS CHAR(8))

        --NUMBER OF KHO IN 1 CUA HANG
        SET @NUM1 = CAST(RAND()*5+1 AS INT) 
        SET @COUNT1 = 0

        DELETE FROM @NK_DATE
        SET @STARTDATE = '2015/01/01'

        WHILE @COUNT1 < @NUM1
        BEGIN
            SET @COUNT1 += 1
            SET @MAKHO = 'KHO' + CAST(@COUNT1 AS CHAR(7))

            -- NUMBER OF SANPHAM IN A KHO
            SET @NUM2 = CAST(RAND()*100 + 50 AS INT)
            SET @COUNT2 = 0
            
            

            WHILE @COUNT2 < @NUM2
            BEGIN
                SET @COUNT2 += 1

                SET @MASP = 'SP' + CAST(CAST(RAND()*@LENGTHSP +1 AS INT) AS CHAR(8))
                SET @SL = CAST(RAND()*1000+10 AS INT)

                INSERT INTO KHO VALUES(@MACH, @MAKHO, @MASP, @SL)
                
                SET @MANHAPKHO = 'NK' + CAST(@COUNT2 AS CHAR(8))

                SET @SLNHAP = CAST(RAND()*@SL*0.75 + 1 AS INT)

                --GENERATE NGAYNHAP
                IF @COUNT1 = 1 
                BEGIN
                    SET @NGAYNHAP = DATEADD(DAY, RAND()*30, @STARTDATE)
                    SET @STARTDATE = @NGAYNHAP
                    INSERT INTO @NK_DATE VALUES(@MANHAPKHO, @NGAYNHAP)
                END
                ELSE 
                BEGIN
                    SET @NGAYNHAP = (SELECT NGAYNHAP FROM @NK_DATE
                                    WHERE @MANHAPKHO = MANK)

                    IF @NGAYNHAP is NULL
                    BEGIN
                        SET @NGAYNHAP = DATEADD(DAY, RAND()*30, @STARTDATE)
                        SET @STARTDATE = @NGAYNHAP
                        INSERT INTO @NK_DATE VALUES(@MANHAPKHO, @NGAYNHAP)
                    END
                END

                INSERT INTO NHAPKHO VALUES(@MACH, @MANHAPKHO , @MAKHO,
                    @MASP, @NGAYNHAP, @SLNHAP)
            END
        END
    END 
END
GO

GO
CREATE PROC INSERTDB
AS BEGIN
    EXEC INSERTKH 500000
    EXEC INSERTSP 10000
    EXEC INSERTCH 1000
    EXEC INSERTNV 5000
    EXEC INSERTLSLUONG 50000
    EXEC INSERTDIEMDANH 100000
    EXEC INSERTDH 2000000
    EXEC INSERTCT_DH
    EXEC INSERTGIAOHANG 500000
    EXEC INSERTKHO_NHAPKHO
END
GO

EXEC INSERTDB
GO
