USE CONCUNG 
GO

CREATE TABLE CT_DONHANG_NOIX
(
	MADH CHAR(10),
	MASP CHAR(10),
	SOLUONG INT,
	THANHTIEN MONEY
	CONSTRAINT PK_CTDONHANG_NOIX PRIMARY KEY(MADH, MASP)
)
GO

GO
CREATE TABLE DONHANG_NOIX
(
	MADH CHAR(10),
	MAKH CHAR(10),
	TIENHANG MONEY,
	PHIVANCHUYEN MONEY,
	TONGTIEN MONEY,
	NVLAPDH CHAR(10),
	NGAYLAP DATE,
	TRANGTHAI BIT, -- TINH TRANG CUA DON HANG
	CONSTRAINT PK_DONGHANG_NOIX PRIMARY KEY(MADH)
)
GO

INSERT INTO DONHANG_NOIX
SELECT * FROM DONHANG

INSERT INTO CT_DONHANG_NOIX
SELECT * FROM CT_DONHANG

go
CREATE TABLE SANPHAM_NOIX
(
	MASP CHAR(10),
	TENSP NVARCHAR(100),
	GIABAN MONEY,
	TENTHUONGHIEU NVARCHAR(100),
	XUATXUTHUONGHIEU NVARCHAR(100),
	XUATXUSP NVARCHAR(100),
	IMAGEURL CHAR(256), -- URL CUA ANH
	MOTASP VARCHAR(max),  --VARCHAR ĐỂ DỄ GENERATE DỮ LIỆU LỚN( STRING 8000 KÍ TỰ )
	MALOAI CHAR(10),
	CONSTRAINT PK_SANPHAM_NOIX PRIMARY KEY(MASP)
)
GO

CREATE TABLE LOAISP_NOIX
(
	MALOAI CHAR(10),
	TENLOAI NVARCHAR(64),
	IMAGEURL CHAR(256)
	CONSTRAINT PK_LOAISP_NOIX PRIMARY KEY(MALOAI)
)


INSERT INTO LOAISP_NOIX
SELECT * FROM LOAISP

INSERT INTO SANPHAM_NOIX
SELECT *FROM SANPHAM
GO

go

CREATE NONCLUSTERED INDEX NIX_TENSP_SP
ON SANPHAM(TENSP) INCLUDE (GIABAN, IMAGEURL)



SELECT TENSP, GIABAN, IMAGEURL FROM SANPHAM
WHERE TENSP LIKE 'a'

SELECT TENSP, GIABAN, IMAGEURL FROM SANPHAM_NOIX
WHERE TENSP LIKE 'a'


GO

SELECT SP.TENSP, SP.GIABAN, SP.IMAGEURL
FROM LOAISP L, SANPHAM SP
WHERE L.MALOAI = 'LOAI1' 

SELECT SP.TENSP, SP.GIABAN, SP.IMAGEURL
FROM LOAISP_NOIX L, SANPHAM_NOIX SP
WHERE L.MALOAI = 'LOAI1' 

GO

CREATE NONCLUSTERED INDEX NIX_THH_SP
ON SANPHAM(TENTHUONGHIEU) INCLUDE (TENSP, GIABAN, IMAGEURL)

SELECT TENSP, GIABAN, IMAGEURL FROM SANPHAM
WHERE TENTHUONGHIEU LIKE N'S'

SELECT TENSP, GIABAN, IMAGEURL FROM SANPHAM_NOIX
WHERE TENTHUONGHIEU LIKE N'S'


GO

CREATE NONCLUSTERED INDEX NIX_KH_DH
ON DONHANG(MAKH)

SELECT * FROM DONHANG
WHERE MAKH = 'KH1'

SELECT * FROM DONHANG_NOIX
WHERE MAKH = 'KH1'


GO
CREATE NONCLUSTERED INDEX NIX_MASP_CT_DH
ON CT_DONHANG(MASP)

CREATE NONCLUSTERED INDEX NIX_MASP_CT_DH_NOIX
ON CT_DONHANG_NOIX(MASP) INCLUDE(SOLUONG, THANHTIEN)



SELECT * FROM CT_DONHANG CT, SANPHAM SP
WHERE CT.MASP = SP.MASP

SELECT * FROM CT_DONHANG_NOIX CT, SANPHAM SP
WHERE CT.MASP = SP.MASP